network.client.threads.ratio = 4

logging.level.org.springframework.web=INFO
logging.level.org.apache.hc.client5.http.wire=WARN
logging.level.org.apache.hc.client5.http.headers=WARN

dataWarehouse.driver.class=org.postgresql.Driver
dataWarehouse.url=jdbc:postgresql://localhost:5432/blueberry
dataWarehouse.user=wangyuqian
dataWarehouse.password=

clickhouse.url=jdbc:clickhouse://localhost:8123/blueberry
clickhouse.user=default
clickhouse.password=default

tu.share.token =be063bdbb78a719187e5165a7c80d651c4caccac8b38a1249144391d

tasks.switch.stock.code.list = false
tasks.switch.stock.snapshot = false
tasks.switch.convert.bond.code.list = false
tasks.switch.stock.k.line = false
tasks.switch.stock.dividends = true
tasks.switch.convertible.bond.history = false
tasks.switch.financial.indicators = false
